title: Hi, I’m Kristian Noprianto
description: Software Developer • Real-Time Systems • Scientific Computing • Backend & Frontend Engineering
remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme
